/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Gelatofied, GelatofiedInterface } from "../Gelatofied";

const _abi = [
  {
    inputs: [],
    name: "gelato",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Gelatofied__factory {
  static readonly abi = _abi;
  static createInterface(): GelatofiedInterface {
    return new utils.Interface(_abi) as GelatofiedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Gelatofied {
    return new Contract(address, _abi, signerOrProvider) as Gelatofied;
  }
}
