/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICounter, ICounterInterface } from "../ICounter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "increaseCount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastExecuted",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICounter__factory {
  static readonly abi = _abi;
  static createInterface(): ICounterInterface {
    return new utils.Interface(_abi) as ICounterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICounter {
    return new Contract(address, _abi, signerOrProvider) as ICounter;
  }
}
