/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPokeMe, IPokeMeInterface } from "../IPokeMe";

const _abi = [
  {
    inputs: [],
    name: "getFeeDetails",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPokeMe__factory {
  static readonly abi = _abi;
  static createInterface(): IPokeMeInterface {
    return new utils.Interface(_abi) as IPokeMeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPokeMe {
    return new Contract(address, _abi, signerOrProvider) as IPokeMe;
  }
}
