/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IResolverWithoutTreasury,
  IResolverWithoutTreasuryInterface,
} from "../IResolverWithoutTreasury";

const _abi = [
  {
    inputs: [],
    name: "checker",
    outputs: [
      {
        internalType: "bool",
        name: "canExec",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "execPayload",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "feeToken",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IResolverWithoutTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IResolverWithoutTreasuryInterface {
    return new utils.Interface(_abi) as IResolverWithoutTreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IResolverWithoutTreasury {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IResolverWithoutTreasury;
  }
}
